### PR TITLE
Fix/422 post application

### LINKED ISSUE #422: FIX POST Application
## Expected behavior

When using the post application endpoint, all transferred data should be used (e.g. services).

## Actual behavior [in case of an issue]

The applications service list is ignored.

## How can the issue be reproduced [in case of an issue]?

Try the promote next version button in #421

### PR DESCRIPTION
**Pull request by davidkopp**
- [x] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [x] Ensure to use auto format in **all** files
- [x] Tests created for changes
- [x] Test created for endpoint `addServiceToApplication`
- [x] Refactor `ApplicationController` → all private methods should be at the bottom

---

## Short Description

Validates provided service (list) if a MicoApplication is created or updated.
Affected endpoint methods:
* POST `createApplication`
* PUT `updateApplication`
* POST `addServiceToApplication`

## Resolving Issue/ Feature

Resolves #422

### CODE REVIEW

**Comment by davidkopp** [comment]
@gepperho 
I created a new namespace with the name `mico-testing-fix-422` in our cluster that runs `mico-core` with the changes from this pull request.

You can check the changes by executing
```
kubectl port-forward svc/mico-core -n mico-testing-fix-422 8080:8080
```

Please note, that I changed the endpoint `addServiceToApplication` from POST to PATCH

File: mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java [hunk 1]
```diff
@@ -139,12 +118,16 @@
             throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Application shortName or version does not match request body.");
         }
 
-        Optional<MicoApplication> applicationOptional = applicationRepository.findByShortNameAndVersion(shortName, version);
-        if (!applicationOptional.isPresent()) {
+        Optional<MicoApplication> existingApplicationOptional = applicationRepository.findByShortNameAndVersion(shortName, version);
+        if (!existingApplicationOptional.isPresent()) {
             throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Application '" + shortName + "' '" + version + "' was not found!");
         }
+        for (MicoService providedService : application.getServices()) {
```
Comment (buehlefs) [inline mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java]: PUT endpoint should NOT update service list of existing application. The service list can already be manipulated with different endpoints so there is no need for put to also do this. And providing two ways of doing the same thing may be confusing. Also what would happen if the Provided application for this endpoint for some reason has no services?
In short: the PUT endpoint for applications should ignore the services completely!

File: mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java [hunk 2]
```diff
@@ -256,6 +239,96 @@
...
+    }
+
+    /**
+     * Returns a list of services associated with the mico application specified by the parameters.
+     *
+     * @param shortName the name of the application
+     * @param version   the version of the application
+     * @return the list of mico services that are associated with the application
+     */
+    @GetMapping("/{" + PATH_VARIABLE_SHORT_NAME + "}/{" + PATH_VARIABLE_VERSION + "}/" + PATH_SERVICES)
```
Comment (buehlefs) [inline mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java]: When reordering endpoints put GET as the first endpoint of all endpoints that share the same path.

File: mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java [hunk 3]
```diff
@@ -256,6 +239,96 @@
...
+        List<MicoApplication> micoApplicationList = applicationRepository.findByShortName(shortName);
+
+        List<Resource<MicoApplication>> applicationResourceList = getApplicationResourceList(micoApplicationList);
+
+        return ResponseEntity.ok(
+            new Resources<>(applicationResourceList,
+                linkTo(methodOn(ApplicationController.class).getApplicationsByShortName(shortName)).withSelfRel()));
+    }
+
+    @PatchMapping("/{" + PATH_VARIABLE_SHORT_NAME + "}/{" + PATH_VARIABLE_VERSION + "}/" + PATH_SERVICES)
```
Comment (buehlefs) [inline mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java]: This should be a PostMapping.
The PATCH method would require a providing a set of changes (such as adding or removing a service) instead of just a service by specification [RFC 5789](https://tools.ietf.org/html/rfc5789#page-2).
POST also matches a generic "add this" semantic (see [specification](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html) and [prior discussion](https://github.com/UST-MICO/mico/pull/270#discussion_r251195349)) without the need to provide a spechial patch document.

File: mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java [hunk 4]
```diff
@@ -256,6 +239,96 @@
...
+        }
+        validateProvidedService(service);
+
+        MicoApplication application = applicationOptional.get();
+        if (!application.getServices().contains(service)) {
+            log.info("Add service '" + service.getShortName() + "' '" + service.getVersion() +
+                "' to application '" + applicationShortName + "' '" + applicationVersion + "'.");
+            application.getServices().add(service);
+            applicationRepository.save(application);
+        } else {
```
Comment (wagnerdk) [inline mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java]: Is the error in the else case not a potential 4XX error? Is there intentionally no return to make the request idempotent? Also, you could consider using the warning log level, because the UI should not allow adding a service to an application if it already exists. This state could indicate an error.

File: mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTests.java [hunk 5]
```diff
@@ -169,7 +175,7 @@ public void getApplicationByShortName() throws Exception {
 
     @Test
     public void getApplicationByShortNameWithTrailingSlash() throws Exception {
-        given(applicationRepository.findByShortName(SHORT_NAME)).willReturn(Collections.singletonList(new MicoApplication().setShortName(SHORT_NAME).setVersion(VERSION)));
+        given(applicationRepository.findByShortName(SHORT_NAME)).willReturn(CollectionUtils.listOf(new MicoApplication().setShortName(SHORT_NAME).setVersion(VERSION)));
```
Comment (wagnerdk) [inline mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTests.java]: Is there a reason to change Collections.singletonList to CollectionUtils.listOf ?

File: mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java (hunk 4 above)
Comment (buehlefs) [reply mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java]: I would be in favor of idempotent bahaviour here

Comment (davidkopp) [reply mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java]: If we created a complete new resource, I would throw a 409 Conflict error. However here we just want to create a link between two existing resources. I think it does not make sense to throw an error if this link is already there.

File: mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTests.java (hunk 5 above)
Comment (davidkopp) [reply mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTests.java]: I changed it only to be consistent. We use `CollectionUtils.listOf` at all other places to also support the creation of a list with multiple elements. I'm aware of that it is in comparison with `Collections.singletonList` not immutable, but that should be no problem.
