### PR TITLE
Fix max size limit of shortNames

### LINKED ISSUE #560: Ensure shortName can be used as Kubernetes label values
Currently we use the pattern of Kubernetes names for the validations of the short name of a *MicoApplication*, *MicoService* and *MicoServiceInterface*. With this pattern a max length of 253 is allowed.
However we also use these names as the value of Kubernetes labels where the max length is 63.

Depends on #512.

### PR DESCRIPTION
**Pull request by wagnerdk**
- [X] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [X] Ensure to use auto format in **all** files
- [X] Tests created for changes or:
  - [ ] Test cases are missing - opened issue for that:
  - [ ] Reason for missing tests:
- [ ] Screenshots added (for UI changes)
- [ ] Change in CHANGELOG.md described

---

## Short Description

Sets the new max size for shortNames to ~~63~~. A limit of 54 is necessary because a UID is generated and concatenated with the shortName to form a label.

## Resolving Issue/ Feature

Closes #560

### CODE REVIEW

File: mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoApplicationRequestDTO.java [hunk 1]
```diff
@@ -60,12 +61,12 @@
             @ExtensionProperty(name = "title", value = "Short Name"),
             @ExtensionProperty(name = "pattern", value = Patterns.KUBERNETES_NAMING_REGEX),
             @ExtensionProperty(name = "minLength", value = "3"),
-            @ExtensionProperty(name = "maxLength", value = "253"),
+            @ExtensionProperty(name = "maxLength", value = KubernetesNameNormalizer.MAX_LABLE_SIZE+""),
```
Comment (davidkopp) [inline mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoApplicationRequestDTO.java]: `+""`?

File: mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoServiceInterfaceRequestDTO.java [hunk 2]
```diff
@@ -62,10 +64,13 @@
             @ExtensionProperty(name = "title", value = "Service Interface Name"),
             @ExtensionProperty(name = "pattern", value = Patterns.KUBERNETES_NAMING_REGEX),
             @ExtensionProperty(name = "x-order", value = "20"),
-            @ExtensionProperty(name = "description", value = "The name of this MicoServiceInterface")
+            @ExtensionProperty(name = "description", value = "The name of this MicoServiceInterface"),
+            @ExtensionProperty(name = "minLength", value = "3"),
+            @ExtensionProperty(name = "maxLength", value = KubernetesNameNormalizer.MAX_LABLE_SIZE+""),
```
Comment (davidkopp) [inline mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoServiceInterfaceRequestDTO.java]: `+""`?

File: mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoServiceRequestDTO.java [hunk 3]
```diff
@@ -69,12 +70,12 @@
             @ExtensionProperty(name = "title", value = "Short Name"),
             @ExtensionProperty(name = "pattern", value = Patterns.KUBERNETES_NAMING_REGEX),
             @ExtensionProperty(name = "minLength", value = "3"),
-            @ExtensionProperty(name = "maxLength", value = "253"),
+            @ExtensionProperty(name = "maxLength", value = KubernetesNameNormalizer.MAX_LABLE_SIZE+""),
```
Comment (davidkopp) [inline mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoServiceRequestDTO.java]: `+""`?

File: mico-core/src/main/java/io/github/ust/mico/core/util/KubernetesNameNormalizer.java [hunk 4]
```diff
@@ -37,6 +37,7 @@
     private final static String REGEX_MULTIPLE_DASHES = "[-]+";
     private final static String REGEX_FIRST_OR_LAST_CHAR_IS_A_DASH = "^-|-$";
     private final static String REGEX_MATCH_VALID_FIRST_CHAR = "^[a-z]+.*";
+    public final static int MAX_LABLE_SIZE = 54;
```
Comment (davidkopp) [inline mico-core/src/main/java/io/github/ust/mico/core/util/KubernetesNameNormalizer.java]: Fix typo → `MAX_LABEL_SIZE`.
However I would prefer a different name like `MICO_NAME_MAX_SIZE`.

Comment (davidkopp) [reply mico-core/src/main/java/io/github/ust/mico/core/util/KubernetesNameNormalizer.java]: Add a JavaDoc to this variable and explain, why it is 54. Example:
A max limit of the MICO names (`{@link MicoApplication}`, `{@link MicoService}` and `{@link MicoServiceInterface}`) is required because they are used as values of Kubernetes labels that have a limit of 63. Furthermore the name is used to create a UID that adds 9 characters to it. Therefore the limit have to be set to 54.

File: mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoApplicationRequestDTO.java (hunk 1 above)
Comment (wagnerdk) [reply mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoApplicationRequestDTO.java]: The value hast to be a string while the constant is an int.
