### PR TITLE
Fix is application deployed

### LINKED ISSUE #409: Application Deployment Information
As a backend developer, I want to know if an application is at the moment deployed, so that I can fulfill e.g. delete requirements.

### LINKED ISSUE #438: Fix check if application is deployed
Implementation in the pull requests only checks for each service of the application if it is deployed. This will break in the extended scenario #390 as a service can be used by multiple applications.

_Originally posted by @buehlefs in https://github.com/UST-MICO/mico/issues/409#issuecomment-464084731_

### PR DESCRIPTION
**Pull request by davidkopp**
- [x] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [x] Ensure to use auto format in **all** files
- [x] Tests created for changes

---

## Short Description

Checks if an application is deployed based on the actual Kubernetes resource names.
Includes many more bug fixes.

## Resolving Issue/ Feature

Resolves #409 
Resolves #438

### CODE REVIEW

File: mico-core/src/main/java/io/github/ust/mico/core/model/MicoServiceDeploymentInfo.java [hunk 1]
```diff
@@ -104,66 +108,80 @@
...
-     */
-    public enum RestartPolicy {
-
-        ALWAYS,
-        ON_FAILURE,
-        NEVER
-        
+    public MicoServiceDeploymentInfo applyValuesFrom(MicoServiceDeploymentInfoResponseDTO serviceDeploymentInfoDto) {
+        return applyValuesFrom((MicoServiceDeploymentInfoRequestDTO) serviceDeploymentInfoDto)
+            .setKubernetesDeploymentInfo(serviceDeploymentInfoDto.getKubernetesDeploymentInfo() == null ? null
```
Comment (buehlefs) [inline mico-core/src/main/java/io/github/ust/mico/core/model/MicoServiceDeploymentInfo.java]: refactor ternary operator into temporary variable
