### PR TITLE
Fix/793 endpoint delete kf connector

### LINKED ISSUE #793: Change endpoint for deleting KafkaFaasConnector from an application
Depends on #790.

Change the endpoint of the method `deleteKafkaFaasConnectorInstanceFromApplication` to
the path `/<short-name>/<version>/kafka-faas-connector/<kf-connector-version>/<instance-id>` (adding path variable `kf-connector-version`)

### PR DESCRIPTION
**Pull request by davidkopp**
# Description

Added new API endpoints:
- `DELETE /applications/<application-short-name>/<application-version>/kafka-faas-connector`
- `DELETE /applications/<application-short-name>/<application-version>/kafka-faas-connector/<kafka-faas-connector-version>`
- `DELETE /applications/<application-short-name>/<application-version>/kafka-faas-connector/<kafka-faas-connector-version>/<instance-id>`

- [ ] this PR contains breaking changes!

# Resolves / is related to

Closes #793 

# What is affected by this PR

- [x] Backend
    - [ ] Kubernetes logic
    - [ ] Domain model
- [x] API
    - [x] discussed changes in the team / informed the team about changes
    - [ ] updated [`insertTestValues.sh`](https://github.com/UST-MICO/mico/blob/master/insertTestValues.sh) and [Postman Collections](https://github.com/UST-MICO/docs/tree/master/debugging-testing/postman) are updated
- [ ] Frontend
    - [ ] Ensure that it is compilable for production (`npm run build -- --prod`)
- [ ] Documentation

# Checklist

- [x] Ensure that new source files include the [license header](https://github.com/UST-MICO/mico/blob/master/CONTRIBUTING.md#source-file-headers)
- [x] Ensure [JavaDoc is up to date](https://github.com/UST-MICO/mico/tree/master/docs#build-the-documentation-locally)

### CODE REVIEW

File: mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java [hunk 1]
```diff
@@ -400,6 +403,96 @@ public void removeKafkaFaasConnectorInstanceFromMicoApplicationByInstanceId(
...
+     */
+    public void removeKafkaFaasConnectorInstancesFromMicoApplicationByVersion(
+        String applicationShortName, String applicationVersion, String kfConnectorVersion)
+        throws MicoApplicationNotFoundException, MicoApplicationIsNotUndeployedException {
+
+        // Retrieve application from database (checks whether it exists)
+        MicoApplication micoApplication = getMicoApplicationByShortNameAndVersion(applicationShortName, applicationVersion);
+
+        // Check whether application is currently undeployed, if not it is not allowed to remove a KafkaFaasConnector instance from the application
+        if (!micoKubernetesClient.isApplicationUndeployed(micoApplication)) {
```
Comment (buehlefs) [inline mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java]: This check should probably be a utility method by now...

File: mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java [hunk 2]
```diff
@@ -400,6 +403,96 @@ public void removeKafkaFaasConnectorInstanceFromMicoApplicationByInstanceId(
         // TODO: Update Kubernetes deployment (see issue mico#627)
     }
 
+    /**
+     * Removes KafkaFaasConnector instances from the {@code kafkaFaasConnectorDeploymentInfos} of the {@link MicoApplication}
+     * that are used in the requested version.
```
Comment (buehlefs) [inline mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java]: Removes all ... that have the requested version. Would be easier to understand (if that is the actual intention of the method)
